### ISSUE TITLE
Critical Error with GB Pro ver2 beta2: Undefined Function acf_get_meta() When ACF is Not Installed

### ISSUE THREAD

**Issue by vburdyko** [tomusborne/generateblocks#1559]
### Description
GenerateBlocks 2.0 beta 2
WordPress 6.7.1
WP Engine Hosting

I'm using a dynamic tag to display the author's name: {{author_meta key:display_name}}. 

Everything works correctly. However, as soon as I enable GenerateBlocks Pro ver2 beta 2, a critical error occurs:

`[Tue Dec 03 13:29:44.832978 2024] [php:error] [pid 30986] [client 35.197.64.146:0] PHP Fatal error:  Uncaught Error: Call to undefined function acf_get_meta() in /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks-pro/includes/extend/dynamic-tags/class-acf.php:130\nStack trace:\n#0 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks-pro/includes/extend/dynamic-tags/class-acf.php(188): GenerateBlocks_Pro_Dynamic_Tags_ACF->maybe_get_field(NULL, '4', 'display_name', 'user')\n#1 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks-pro/includes/extend/dynamic-tags/class-acf.php(68): GenerateBlocks_Pro_Dynamic_Tags_ACF->get_user_meta_pre_value(NULL, '4', 'display_name')\n#2 /nas/content/live/rowingmach1dev/wp-includes/class-wp-hook.php(324): GenerateBlocks_Pro_Dynamic_Tags_ACF->get_meta_pre_value(NULL, '4', 'display_name', 'get_user_meta')\n#3 /nas/content/live/rowingmach1dev/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)\n#4 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks/includes/class-meta-handler.php(200): apply_filters('generateblocks_...', NULL, '4', 'display_name', 'get_user_meta')\n#5 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks/includes/class-meta-handler.php(296): GenerateBlocks_Meta_Handler::get_meta('4', 'display_name', true, 'get_user_meta')\n#6 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks/includes/dynamic-tags/class-dynamic-tag-callbacks.php(466): GenerateBlocks_Meta_Handler::get_user_meta('4', 'display_name')\n#7 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks/includes/dynamic-tags/class-register-dynamic-tag.php(174): GenerateBlocks_Dynamic_Tag_Callbacks::get_author_meta(Array, Array, Object(WP_Block))\n#8 /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks/includes/dynamic-tags/class-dynamic-tags.php(354): GenerateBlocks_Register_Dynamic_Tag::replace_tags('\\n<p class="gb-t...', Array, Object(WP_Block))\n#9 /nas/content/live/rowingmach1dev/wp-includes/class-wp-hook.php(324): GenerateBlocks_Dynamic_Tags->replace_tags('\\n<p class="gb-t...', Array, Object(WP_Block))\n#10 /nas/content/live/rowingmach1dev/wp-includes/plugin.php(205): WP_Hook->apply_filters('\\n<p class="gb-t...', Array)\n#11 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(566): apply_filters('render_block', '\\n<p class="gb-t...', Array, Object(WP_Block))\n#12 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#13 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#14 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#15 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#16 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#17 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#18 /nas/content/live/rowingmach1dev/wp-includes/class-wp-block.php(499): WP_Block->render()\n#19 /nas/content/live/rowingmach1dev/wp-includes/blocks.php(2061): WP_Block->render()\n#20 /nas/content/live/rowingmach1dev/wp-includes/blocks.php(2113): render_block(Array)\n#21 /nas/content/live/rowingmach1dev/wp-includes/class-wp-hook.php(324): do_blocks('<!-- wp:generat...')\n#22 /nas/content/live/rowingmach1dev/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:generat...', Array)\n#23 /nas/content/live/rowingmach1dev/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:generat...')\n#24 /nas/content/live/rowingmach1dev/wp-content/themes/generatepress/content-page.php(73): the_content()\n#25 /nas/content/live/rowingmach1dev/wp-includes/template.php(812): require('/nas/content/li...')\n#26 /nas/content/live/rowingmach1dev/wp-includes/template.php(745): load_template('/nas/content/li...', false, Array)\n#27 /nas/content/live/rowingmach1dev/wp-includes/general-template.php(206): locate_template(Array, true, false, Array)\n#28 /nas/content/live/rowingmach1dev/wp-content/themes/generatepress/inc/theme-functions.php(568): get_template_part('content', 'page')\n#29 /nas/content/live/rowingmach1dev/wp-content/themes/generatepress/page.php(34): generate_do_template_part('page')\n#30 /nas/content/live/rowingmach1dev/wp-includes/template-loader.php(106): include('/nas/content/li...')\n#31 /nas/content/live/rowingmach1dev/wp-blog-header.php(19): require_once('/nas/content/li...')\n#32 /nas/content/live/rowingmach1dev/index.php(17): require('/nas/content/li...')\n#33 {main}\n  thrown in /nas/content/live/rowingmach1dev/wp-content/plugins/generateblocks-pro/includes/extend/dynamic-tags/class-acf.php on line 130`

ACF is not installed, but if it is installed, everything works correctly.

### Steps to reproduce
1. Add the dynamic tag {{author_meta key:display_name}}, other keys can be used, and the same issue occurs with them.
2. Make sure ACF is not installed in this WP installation. 
3. Save the page. 
4. A critical error occurs when opening or editing this page.

The issue might be with the WP Engine hosting, because everything works correctly on the local WP copy, both with and without ACF.

**Comment by vburdyko** [comment]
Resolved, the issue was caused by a conflict with the "AmaLinks Pro" plugin.
