### ISSUE TITLE
Query Block - multiple taxonomy parameters returns fatal error 

### ISSUE THREAD

**Issue by diggeddy** [tomusborne/generateblocks#1572]
### Description
Setting multiple taxonomy parameters , eg a Category and a Tag will result in a Fatal error.
Example set up:

<img width="210" alt="Screenshot 2024-12-06 at 16 23 25" src="https://github.com/user-attachments/assets/54bf925f-3542-41c7-acd2-df6490a235fc">

Example error 

```
Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-pro-release-1.8.0/includes/extend/query-loop/class-related-terms.php:69 Stack trace: #0 [internal function]: GenerateBlocks_Pro_Related_Terms::{closure}('AND') #1 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-pro-release-1.8.0/includes/extend/query-loop/class-related-terms.php(88): array_map(Object(Closure), Array) #2 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-pro-release-1.8.0/includes/extend/query-loop/class-related-terms.php(38): GenerateBlocks_Pro_Related_Terms::add_current_post_terms(Array, 'tax_query') #3 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/class-wp-hook.php(326): GenerateBlocks_Pro_Related_Terms::include_current_post_terms(Array) #4 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) #5 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-release-2.0.0/includes/class-query-utils.php(227): apply_filters('generateblocks_...', Array, Array, Object(WP_Block)) #6 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-release-2.0.0/includes/blocks/class-query.php(69): GenerateBlocks_Query_Utils::get_wp_query_args(Array, 1, Array, Object(WP_Block)) #7 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-release-2.0.0/includes/blocks/class-query.php(115): GenerateBlocks_Block_Query::get_query_data('WP_Query', Array, Object(WP_Block), 1) #8 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/class-wp-block.php(537): GenerateBlocks_Block_Query::render_block(Array, '\n<div><div clas...', Object(WP_Block)) #9 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/blocks.php(2190): WP_Block->render() #10 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/blocks.php(2242): render_block(Array) #11 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/class-wp-hook.php(324): do_blocks('<!-- wp:generat...') #12 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('<!-- wp:generat...', Array) #13 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/post-template.php(256): apply_filters('the_content', '<!-- wp:generat...') #14 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/themes/generatepress/content-single.php(73): the_content() #15 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/template.php(812): require('/Users/diggeddy...') #16 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/template.php(745): load_template('/Users/diggeddy...', false, Array) #17 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/general-template.php(206): locate_template(Array, true, false, Array) #18 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/themes/generatepress/inc/theme-functions.php(568): get_template_part('content', 'single') #19 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/themes/generatepress/single.php(29): generate_do_template_part('single') #20 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-includes/template-loader.php(106): include('/Users/diggeddy...') #21 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-blog-header.php(19): require_once('/Users/diggeddy...') #22 /Users/diggeddylaptop/Local Sites/gblocks2/app/public/index.php(17): require('/Users/diggeddy...') #23 {main} thrown in /Users/diggeddylaptop/Local Sites/gblocks2/app/public/wp-content/plugins/generateblocks-pro-release-1.8.0/includes/extend/query-loop/class-related-terms.php on line 69
```

**Comment by iansvo** [comment]
Seems like the issue is that this query loop filter is running on the query block. I need to look into it further later, but I am not exactly sure we should be keeping that fallback filter after all. There's some solid side effect potential here since the query args aren't  the same between the blocks now.
